AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CodePipeline with existing service roles for CodePipeline and CodeBuild, using a custom ECR image for CodeBuild.

Parameters:
  CodePipelineName:
    Type: String
    Description: Name of the CodePipeline.

  CodePipelineServiceRoleArn:
    Type: String
    Description: ARN of the existing service role for CodePipeline.
    
  CodeBuildServiceRoleArn:
    Type: String
    Description: ARN of the existing service role for CodeBuild.

  ChatbotTargetArn:
    Type: String
    Default: arn:aws:chatbot::<account_number>:chat-configuration/microsoft-teams-channel/AWS-Application-CICD-Notifications

  CodeCommitRepositoryName:
    Type: String
    Description: Name of the CodeCommit repository to use as the source.

  CodeCommitBranchName:
    Type: String
    Default: main
    Description: Name of the CodeCommit Branch to use as the source.

  CodeBuildProjectName:
    Type: String
    Description: Name of the CodeBuild project for building the code.
  
  ScanBuildProjectName:
    Type: String
    Description: Name of the CodeBuild project for scanning the code.

  ImageID:
    Type: String
    Default: aws/codebuild/standard:7.0
    Description: Ubuntu image to use in CodeBuild 

  Buildspec:
    Type: String
    Default: plan.yml
    Description: The path to the buildspec file

  Deployspec:
    Type: String
    Default: apply.yml
    Description: The path to the buildspec file

  Scanspec:
    Type: String
    Default: scan.yml
    Description: The path to the buildspec file for scanning

  SNSTopic:
    Type: String
    Description: SNS topic notification arn

  ReviewComment:
    Type: String
    Default: "For the manual approval process, perform the following actions:  1. Review source code scan result. Visit https://sonarqube.ca 2. Confirm successful deployment to the staging environment 3. Review the build artifacts in s3://devops-pipeline-bucket/project/build_artifacts/prod/"


  EnvironmentVariable1Name:
    Type: String
    Default: SONARQUBE_PROJECT
  EnvironmentVariable1Value:
    Type: String
    Description: The project name in Sonarqube
  EnvironmentVariable2Name:
    Type: String
    Default: SONARQUBE_URL
  EnvironmentVariable2Value:
    Type: String
    Default: https://sonarqube.ca
  EnvironmentVariable3Name:
    Type: String
    Default: SONARQUBE_KEY
  EnvironmentVariable3Value:
    Type: String
    Description: The project unique key generaated in Sonarqube

Resources:
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref CodePipelineName
      RoleArn: !Ref CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref CodeCommitRepositoryName
                BranchName: !Ref CodeCommitBranchName
        - Name: Scan
          Actions:
            - Name: ScanAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: ScanOutput
              Configuration:
                ProjectName: !Ref ScanBuildProjectName
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProjectName
        - Name: Email-Approval
          Actions:
            - Name: Email-Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              Configuration:
                CustomData: !Ref ReviewComment
                NotificationArn: !Ref SNSTopic
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DeployOutput
              Configuration:
                ProjectName: !Ref CodeDeployProjectName
        

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    DeletionPolicy: Retain

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref ImageID
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref Buildspec

  CodeDeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeDeployProjectName
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref ImageID
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref Deployspec

  ScanBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ScanBuildProjectName
      ServiceRole: !Ref CodeBuildServiceRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref ImageID
        EnvironmentVariables:
          - Name: !Ref EnvironmentVariable1Name
            Value: !Ref EnvironmentVariable1Value
          - Name: !Ref EnvironmentVariable2Name
            Value: !Ref EnvironmentVariable2Value
          - Name: !Ref EnvironmentVariable3Name
            Value: !Ref EnvironmentVariable3Value
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref Scanspec

  NotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: !Sub "${CodePipelineName}"
      DetailType: FULL
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-failed
        - codepipeline-pipeline-pipeline-execution-succeeded
        - codepipeline-pipeline-pipeline-execution-started
        - codepipeline-pipeline-action-execution-failed
        - codepipeline-pipeline-action-execution-succeeded
        - codepipeline-pipeline-action-execution-started
        - codepipeline-pipeline-manual-approval-failed
        - codepipeline-pipeline-manual-approval-succeeded
        - codepipeline-pipeline-stage-execution-failed
        - codepipeline-pipeline-stage-execution-succeeded
        - codepipeline-pipeline-stage-execution-started
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipelineName}"
      Targets:
        - TargetType: AWSChatbotMicrosoftTeams
          TargetAddress: !Ref ChatbotTargetArn

Outputs:
  PipelineName:
    Description: The name of the CodePipeline
    Value: !Ref CodePipelineName
